//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace style.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int Code { get; set; }
        public string ItemName { get; set; }
        public string ItemDescription { get; set; }
        public Nullable<double> ItemPrice { get; set; }
        public string Department { get; set; }
        public string logo { get; set; }
    }
}
